### ISSUE TITLE
Suggestion: Installation of Chromium in user mode

### ISSUE THREAD

**Issue by GJKrupa** [UKHomeOffice/developer_user_environments#5]
Suggestion: Installation of Chromium in user mode

## Expected Behavior
Target environment requires a Chrome browser.  Chrome/Chromium browser should be available for testing user interfaces.

## Current Behavior
No Chrome/Chromium browser is present.  Insufficient access to install Chrome .deb package.

## Possible Solution
If Chrome will not be included in a standard Linux build, add installation script for Chromium browser using the URL https://download-chromium.appspot.com/

[chromium.zip](https://github.com/UKHomeOffice/developer_user_environments/files/766367/chromium.zip)

## Context
Developing specifically for a Chrome target environment, testing using FireFox is adequate but a Chrome browser would be more representative of the end-user experience.

## Your Environment

* Ubuntu 16.04 development laptop

**Comment by pixie79** [comment]
Chrome is installed by default on the latest builds
